### ISSUE TITLE
InvalidResponseException

### ISSUE THREAD

**Issue by J-Brk** [api-postcode/api-postcode-laravel#1]
ApiPostcode \ Exception \ InvalidResponseException
Response does not return a valid response code

And the documentation page on your website to test the API does not work too.

**Comment by api-postcode** [comment]
Hey mmjjb,

Thank you for opening this issue. 
Your issue is not really clear for me, can you give me some more details?

The InvalidResponseException is not supposed to return a 'valid' response statuscode.
How does your controller method looks like? Do you try catch?

And can you give me some more details about the documentation for testing does not work?
What is not working in the documentation? Or what is not clear for you?

The documentation is not supposed for testing your api btw..

Cheers!
